### ISSUE TITLE
one activity page per primary school module

### ISSUE THREAD

**Issue by adasilva** [physicsmattersmcgill/physicsmattersmcgill#40]
Please check the comments to see if someone is working on each page *before* you start working on it. If no one else has commented, please make a new comment saying that you will work on that page so we don't repeat any work!

Primary modules (will check off once the pull request is approved):
- [x] circuits and electricity
- [x] collisions
- [x] forces and friction
- [x] gravity
- [x] heat and temperature
- [x] magnetism
- [x] sink or float - just needs French title

Here is the page with the activities list: http://physicsmatters.physics.mcgill.ca/activities/

**Comment by adasilva** [comment]
I'll work on the collisions activity - but someone will need to translate when I'm done.

**Comment by adasilva** [comment]
Collisions activity is done in English, needs translation

**Comment by adasilva** [comment]
I am working on circuits now.

**Comment by jenny-xly-long** [comment]
I am working on the "Sink or Float" module.

**Comment by JuliannWray** [comment]
I will translate "collisions".

**Comment by adasilva** [comment]
I added PDFs for "forces & friction" and "gravity" modules in the downloads folder. See the facilitator guide to help writing objectives/summaries.

**Comment by JuliannWray** [comment]
I translated the "circuits and electricity" module.

**Comment by JuliannWray** [comment]
I am working on the "Forces and Friction" module.

**Comment by adasilva** [comment]
@JuliannWray the images for forces and friction are "forcesfriction.jpg" (title image) and "thumb_forcesfriction.jpg" (thumbnail image). (See collisions activity for example.)

**Comment by JuliannWray** [comment]
@adasilva Okay, thanks! I'll send a pull request of an updated copy of the module.

**Comment by adasilva** [comment]
@JuliannWray I think if you just make a new commit to the same branch, it will update the pull request without you having to do a new one.

**Comment by JuliannWray** [comment]
@adasilva Perfect that worked. I may have made some errors in adding the image and downloads section.

**Comment by jenny-xly-long** [comment]
I am working on Heat and Temperature module.

**Comment by adasilva** [comment]
@jenny-xly-long Excellent! Please make sure you get the most recent version - you should see filenames for images in the document. I also just added the PDFs in the downloads folder - please add the appropriate filenames into the file (see collisions activity for example)

**Comment by adasilva** [comment]
I'm going to write something short on Magnetism, but I think this activity will be revised sometime during this year, so I won't add any downloads.

**Comment by JuliannWray** [comment]
I am working on translating the  magnetism activity

**Comment by JuliannWray** [comment]
I am working on the gravity activity.

**Comment by adasilva** [comment]
@jenny-xly-long  are you still working on heat & temp?

**Comment by adasilva** [comment]
Thanks so much @jenny-xly-long and @JuliannWray! Well done!
