### ISSUE TITLE
translation of interns page

### ISSUE THREAD

**Issue by adasilva** [physicsmattersmcgill/physicsmattersmcgill#46]
Translation needed on `pages/interns_fr.md` (replace the English in that file with French version.)

**Comment by adasilva** [comment]
Also: need to translate the title in the navigation menu ("Summer Internships" in the "Pour les élèves" drop-down menu)

**Comment by adasilva** [comment]
@JuliannWray now that activities are done, if you have time, there are more translations you could work on - e.g. this one.

**Comment by jenny-xly-long** [comment]
I have translated the "intern" page.
