### ISSUE TITLE
Can't push on master

### ISSUE THREAD

**Issue by achuinar** [physicsmattersmcgill/physicsmattersmcgill#9]
Hi Ashley,
Tried to push a commit on master but it gives me this:

remote: Permission to physicsmattersmcgill/physicsmattersmcgill.git denied to achuinar.
fatal: unable to access 'https://github.com/physicsmattersmcgill/physicsmattersmcgill.git/': The requested URL returned error: 403

I guess you have to change the  permissions.
Cheers,
A

**Comment by adasilva** [comment]
try now - i gave all organization members write access.

**Comment by adasilva** [comment]
Issue resolved.
